spring:
  datasource:
    url: jdbc:mariadb://fakedeveloper-1.cntzqxmv6ryr.ap-northeast-2.rds.amazonaws.com:3306/ddangddangmarket
    username: fakedev
    password: alstjd1234
  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
