# 이 파일은 hibernate 연결할때 설정하세요!
# Mac OS Program Argument 설정
# Run > Edit Configuration > Enviroment > Program Argument 설정
# 해당 Argument는 Main함수의 Parameter로 넘어가게 됨
 spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true
    # 현재 우리가 사용하는 DBMS 지정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
